# Generated by Django 3.2.8 on 2021-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20211023_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ImageField(upload_to='static/img/images'),
        ),
    ]
