# Generated by Django 3.2.8 on 2021-10-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20211023_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='picture',
        ),
    ]
