# Generated by Django 3.2.8 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='picture',
            field=models.ImageField(default='static/img/images/naruto-smiling-naruto-33926978-940-850.jpg', upload_to='static/img/images'),
        ),
    ]
