# Generated by Django 3.2.8 on 2021-10-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_alter_entry_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='isbookmark',
            field=models.BooleanField(default=False),
        ),
    ]
