# Generated by Django 3.2.8 on 2021-10-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_entry_isbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
