# Generated by Django 3.2.8 on 2021-10-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_entry_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-completed', '-updated', '-created']},
        ),
    ]
