# Generated by Django 3.2.8 on 2021-10-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['completed', '-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ImageField(blank=True, default='static/img/images/6a63572fa8d7c63d89fb237b6e4e8bw.jpg', null=True, upload_to='static/img/images'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.entry')),
            ],
        ),
    ]
