# Generated by Django 3.2.8 on 2021-10-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20211027_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.collection'),
        ),
    ]
