# Generated by Django 3.2.8 on 2021-10-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20211028_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='collection',
        ),
        migrations.AddField(
            model_name='entry',
            name='collection',
            field=models.ManyToManyField(to='diary.Collection'),
        ),
    ]
